var myAge = 31;
var favoriteNumber = 23;
var momsAge = 67;
var dadsAge = 67;
var favoriteSaying = "The rest of my life will be the best of my life.";
var favoriteCar = "Grand National";
var favoriteColor = "Blue";
var onTimeToday = true;
var onTimeTomorrow = false;
var currentMood = undefined;

console.log("I am " + myAge + " years old.");
console.log("My favorite number is " + favoriteNumber + ".");
console.log("My mother is currently " + momsAge + " years old.");
console.log("My father is currently " + dadsAge + " years old.");
console.log("This is my favorite saying: " + favoriteSaying);
console.log(favoriteCar + " is my favorite car of all time!.");
console.log(favoriteColor + " is my favorite color!.");
console.log("Did I show up on time today? " + onTimeToday);
console.log("Will I show up on time tomorrow? " + onTimeTomorrow);
console.log("My current mood is always " + currentMood);